### ISSUE TITLE
example order is created backwards

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#23]
When creating a checkmark activity, it is possible to set the "Number of examples" and the "Number of first example"

However, after creating, the order of the examples is always backwards and has to be manually changed again in the settings in order to get them into the right order.

**Comment by phager-at** [comment]
Hi,

I just tested this (especially for you on my postgres-based instance) and the mentioned behavior could not be reproduced. Can you give us more details about it? Do you have special DB-configuration which may cause this behaviour? Usually we fetch the examples from the DB without ordering them separately. So if your DB gives us back the examples in a distinct order, we use that order to present the examples.

**Comment by stemiwe** [comment]
we do not have any special DB configuration and never encountered any DB-based problems except with this plugin

creating the activity:
![image](https://user-images.githubusercontent.com/13886080/32783130-f8bccfb4-c94a-11e7-9c7a-1cc677ba025f.png)

immediately afterwards displaying it:
![image](https://user-images.githubusercontent.com/13886080/32783161-0b28a57e-c94b-11e7-851a-fc755f2c721d.png)

editing the settings after creating it:
![image](https://user-images.githubusercontent.com/13886080/32783189-28a35716-c94b-11e7-821b-2228950ab3c2.png)

while making these screenshots, I realized what the problem seems to be: the option "Activate individual function" is activated after creating, even though it was disabled when creating the activity.

If i disable "Activate individual function", the examples appear in the right order

**Comment by stemiwe** [comment]
oh and I should add we are still using version 2017081003 of mod_checkmark

**Comment by phager-at** [comment]
> oh and I should add we are still using version 2017081003 of mod_checkmark

Then you should skip version v3.3.4. :)
I'll add explicit ORDER BY statements to every fetching of the examples from the DB. It seems to me, we were too naive by not sorting the fetched examples - but we didn't have any problems like that in the last years.
The checkbox "activate individual .." is only active due to the examples being fetched in the wrong order, so he doesn't see the standard layout.

I'll try to push the fix ASAP, but it has to go through our testing-team, PO and merging team!

**Comment by phager-at** [comment]
Hi again,

due to our 3.4 release being on the way, we decided to fix it just in 3.4.0 but we also give you the patch to have it fixed in 3.3, though I have to warn you, that the patch hasn't been tested by our testing team yet. Please have a look at https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/commit/26d0a3e0cf067da969bb45b2bfad366aaa36c546 for the 3.3 fix.

If you have installed local_checkmarkreport in addition to mod_checkmark on your system, you should take a look at https://github.com/academic-moodle-cooperation/moodle-local_checkmarkreport/commit/0b3cbb96b314e76829935aed1226e8a441a3bd65 giving you the same fixes for the current Moodle 3.3 compatible version of local_checkmarkreport.

cheers,
Philipp

**Comment by stemiwe** [comment]
thats no problem, we will upgrade to 3.4 anyways, since it contains another fix we want, i was just waiting with the upgrade for this fix to be included as well :)

thx for fixing it that fast

**Comment by phager-at** [comment]
We included the fix for this issue in v3.3.5, despite what we decided before, due to our need of fixing a usability regression!

**Comment by stemiwe** [comment]
was this issue fixed after all?

because we still have the same behaviour in moodle 3.4.2 with checkmark v3.4.1 2018012701

**Comment by stemiwe** [comment]
issue seems fixed in checkmark v3.5, maybe since the way the examples are displayed was improved (a lot) anyways - examples now each have their own column, and appear in the correct order. awesome :)
